<?php

// uncomment the following to define a path alias
//Yii::setPathOfAlias('local','path/to/local-folder');

// This is the main Web application configuration. Any writable
// CWebApplication properties can be configured here.
return array(
    'id'=>'swoper',
    'basePath'=>dirname(__FILE__).DIRECTORY_SEPARATOR.'..',
    'charset'=>'UTF-8',
    'name'=>'LBS Daily Management - UAT',
    'timeZone'=>'Asia/Hong_Kong',
    'sourceLanguage'=> 'hk',
    'language'=>'zh_cn',

    'aliases'=>array(
        'bootstrap'=>realpath(__DIR__.'/../extensions/bootstrap'),
    ),

    // preloading 'log' component
    'preload'=>array('log'),

    // autoloading model and component classes
    'import'=>array(
        'application.models.*',
        'application.components.*',
        'ext.YiiMailer.YiiMailer',
        'bootstrap.helpers.*',
        'bootstrap.widgets.*',
        'bootstrap.components.*',
        'bootstrap.form.*',
        'bootstrap.behaviors.*',
        'application.extensions.phpexcel.*',
    ),

    'modules'=>array(
    ),

    // application components
    'components'=>array(
        'user'=>array(
            // enable cookie-based authentication
            'class'=>'WebUser',
            'allowAutoLogin'=>true,
        ),
        // uncomment the following to enable URLs in path-format

        'urlManager'=>array(
            'urlFormat'=>'path',
//			'showScriptName'=>false,
//			'caseSensitive'=>false,
            'rules'=>array(
                '<controller:\w+>/<id:\d+>'=>'<controller>/view',
                '<controller:\w+>/<action:\w+>/<id:\d+>'=>'<controller>/<action>',
                '<controller:\w+>/<action:\w+>'=>'<controller>/<action>',
            ),
        ),

        'bootstrap'=>array(
//			'class'=>'bootstrap.components.TbApi',
            'class'=>'TbApiEx',
        ),

        // uncomment the following to use a MySQL database
        'db'=>array(
            'connectionString' => 'mysql:host=localhost;dbname=service',
            'emulatePrepare' => true,
            'username' => 'swuser',
            'password' => 'swisher168',
            'charset' => 'utf8',
        ),
		// 'db2'=>array(
  //           'class'=>'CDbConnection',
  //           'connectionString' => 'mysql:host=59.37.134.206;dbname=lbs_xcx',
  //           'emulatePrepare' => true,
  //           'username' => 'lbs_xcx',
  //           'password' => 'A3hWiMeDtEwBcFKY',
  //           'charset' => 'utf8',
  //           'tablePrefix'=>''
  //       ),
        'errorHandler'=>array(
            // use 'site/error' action to display errors
            'errorAction'=>'site/error',
        ),

        'log'=>array(
            'class'=>'CLogRouter',
            'routes'=>array(
                array(
                    'class'=>'CFileLogRoute',
                    'levels'=>'error, warning',
                ),
                // uncomment the following to show log messages on web pages
                array(
                    'class'=>'CWebLogRoute',
                    //	'levels'=>'trace',
                    //	'categories'=>'vardump',
                    //	'showInFireBug'=>true
                ),
            ),
        ),

        'session'=>array(
            'class'=>'CHttpSession',
            'cookieMode'=>'allow',
            'cookieParams'=>array(
                'domain'=>'192.168.0.105',
            ),
        ),
    ),

    // application-level parameters that can be accessed
    // using Yii::app()->params['paramName']
    'params'=>array(
        'adminEmail'=>'it@lbsgroup.com.hk',
        'checkStation'=>false,
        'validRegDuration'=>'3 hours',
        'concurrentLogin'=>false,
        'noOfLoginRetry'=>5,
        'sessionIdleTime'=>'1 hour',
        'version'=>'china',
        'docmanPath'=>'/docman/dev',
        'systemId'=>'svc',
        'envSuffix'=>'uat',
        'table_envSuffix'=>'lbs_service_',
        'appname'=>'LBS DMS (UAT)',
        'appcolor'=>'skin-purple-light',
        'showRank'=>'on',
        'baseUrl_imgs'=>'https://xcx.lbsapps.cn/',//  正式版：https://xcx.lbsapps.cn/ 测试版：https://operation.lbsapps.cn/
        'wss'=>'wss://xcx.lbsapps.cn/wss',
        'cust'=>array(
            "05CBDX30-GZ", //太多了不想写 了 就这样
            "05CBDX03-GZ",
            "05CBBY95-GZ",
            "06CBD96-GZ",
            "01CBDC31-GZ",
            "02CBDX30-GZ",
            "104CBD88-GZ",
            "06CBDX02-GZ",
            "06CBD85-GZ",
            "06CBD84-GZ",
            "06CBD83-GZ",
            "09CBDX01-GZ",
            "09CBDH72-GZ",
            "07CBDL12-GZ",
            "01CBD04-GZ",
            "02CBDX01-GZ",
            "06CBRR91-GZ",
            "06CBD98-GZ",
            "101CBD87-GZ",
            "01CBDX27-GZ",
            "05CBD99-GZ",
            "09CBHY101-GZ",
            "08CBGZ20-GZ",
            "08CBTH74-GZ",
            "08CBXG19-GZ",
            "09CBD80-GZ",
            "09CBDX30-GZ",
            "05CBJC17-GZ",
            "02CBDX02-GZ",
            "07CBKL102-GZ",
            "05CBDX10-GZ",
            "09CBLI89-GZ",
            "101CBLZ71-GZ",
            "101CBLN100-GZ",
            "01CBDX10-GZ",
            "05CBDX01-GZ",
            "06CBD86-GZ",
            "07CBDX01-GZ",
            "05CBMW103-GZ",
            "01CBD94-GZ",
            "03CBDX01-GZ",
            "05CBDX04-GZ",
            "101SYSX01-GZ",
            "101CBCW06-GZ",
            "101CBGJ01-GZ",
            "05CBRZ01-GZ",
            "04CBDX01-GZ",
            "01CBDX28-GZ",
            "08CBDH02-GZ",
            "01CBTS03-GZ",
            "02CBTC32-GZ",
            "01CBD26-GZ",
            "05CBWZ90-GZ",
            "01CBDW01-GZ",
            "07CBDX02-GZ",
            "01CBDX31-GZ",
            "03CBD81-GZ",
            "03CBD82-GZ",
            "06CBDX01-GZ",
            "03CBXB75-GZ",
            "08CBXJ79-GZ",
            "09CBXT13-GZ",
            "09CBWD93-GZ",
            "08CBYL75-GZ",
            "04CBYN92-GZ",
            "03CBDX02-GZ",
            "101CBD97-GZ",
            "05CBDX02-GZ",
            "01CBDX32-GZ",
            "01CBDX08-GZ",
            "06CBYG01-GZ",
            "09CBZJ73-GZ",
            "04CBZS33-GZ",
            "01CBDX01-GZ",
            "11NLCBD1-ZS",
            "17CBD001-ZH",
            "XHCBD001-JM",
            "JMCBD001-JM",
            "JMCBD002-JM",
            "KPCBD001-JM",
            "04CXDT01-SZ",
            "04WYYP01-SZ",
            "02MZHK01-SZ",
            "04CGG001-SZ",
            "05HFS001-SZ",
            "05WHS001-SZ",
            "01LXYP01-SZ",
            "03DDM001-SZ",
            "03BBYP01-SZ",
            "05LXJ001-SZ",
            "05XGC001-SZ",
            "03SMCY01-SZ",
            "01AKYP01-SZ",
            "05HDCY04-SZ",
            "03ZSN001-SZ",
            "07QYYP01-SZ",
            "04GQNC01-SZ",
            "07PSNC01-SZ",
            "02XJD001-SZ",
            "04JAYP01-SZ",
            "05ZDAH01-SZ",
            "05CQD001-SZ",
            "04CBD001-SZ",
            "POCXYP01-SZ",
            "04CGG001-SZ",
            "05HFS001-SZ",
            "05WHS001-SZ",
            "01LXYP01-SZ",
            "04XYCY01-SZ",
            "01XHCY01-SZ",
            "04SQB001-SZ",
            "03DDM001-SZ",
            "01DDX001-SZ",
            "03BBYP01-SZ",
            "05LXJ001-SZ",
            "05XGC001-SZ",
            "04CXDT01-SZ",
            "05YDDX01-SZ",
            "05ZLCY01-SZ",
            "05BSL001-SZ",
            "03SMCY01-SZ",
            "01AKYP01-SZ",
            "POMML001-SZ",
            "04YOMD01-SZ",
            "07PMF001-SZ",
            "05HDCY04-SZ",
            "05YYYP02-SZ",
            "POPPYP01-SZ",
            "03LLC001-SZ",
            "02FZNC01-SZ",
            "03YNYP01-SZ",
            "03GGW001-SZ",
            "04LZH001-SZ",
            "04LQYP01-SZ",
            "05XFNC01-SZ",
            "05XYNC01-SZ",
            "04XTCY01-SZ",
            "04XTCY02-SZ",
            "03CWYP01-SZ",
            "07ZHYC01-SZ",
            "07KDD001-SZ",
            "04XNCY01-SZ",
            "07BDQD01-SZ",
            "07CBD002-SZ",
            "07YRL001-SZ",
            "04LBJ001-SZ",
            "04CBD0004-SZ",
            "07CBD003-SZ",
            "04CBD001-SZ",
            "04XY0001-SZ",
            "05CYYP01-SZ",
            "05GBW001-SZ",
            "05CBD001-SZ",
            "06TSYP01-SZ",
            "03XKL001-SZ",
            "03GHYP01-SZ",
            "03ZSN001-SZ",
            "05SXNC01-SZ",
            "05DDX001-SZ",
            "02FHYP01-SZ",
            "07QYYP01-SZ",
            "04GQNC01-SZ",
            "03CSJ001-SZ",
            "03XHQ001-SZ",
            "04CDYP01-SZ",
            "04CXDT01-SZ",
            "04WYYP01-SZ",
            "02MZHK01-SZ",
            "001CBD-DG",
            "002CBD2-DG",
            "002CBD3-DG",
            "002CBD4-DG",
            "002CBD5-DG",
            "003CBD1-DG",
            "004CBD-DG",
            "004CBD2-DG",
            "004CBD3-DG",
            "004CBD4-DG",
            "004CBD5-DG",
            "004CBD6-DG",
            "005CBD-DG",
            "005CBD1-DG",
            "006CBD-DG",
            "006CBD1-DG",
            "007CBD2-DG",
            "008CBD-DG",
            "009CBD-DG",
            "010CBD-DG",
            "010CBD1-DG",
            "010CBD2-DG",
            "010CBD3-DG",
            "010CBD4-DG",
            "012CBD-DG",
            "014CBD-DG",
            "017CBD-DG",
            "020CBD-DG",
            "022CBD-DG",
            "022CBD1-DG",
            "022CBD2-DG",
            "023CBD-DG",
            "027CBD-DG",
            "030CBD-DG",
            "031CBD-DG",
            "103CBD3-DG",
            "123-ZY"
        ),
    ),
);
